#!/bin/bash
set -e
ADB=${ADB:-adb}
PLAYER=${FFPLAY:-ffplay}
SNDCPY_PORT=${SNDCPY_PORT:-28200}

serial=
if [[ $# -ge 1 ]]
then
    serial="-s $1"
    echo "Waiting for device $1..."
else
    echo 'Waiting for device...'
fi

"$ADB" $serial wait-for-device

"$ADB" $serial forward tcp:$SNDCPY_PORT localabstract:sndcpy
"$ADB" $serial shell am start com.rom1v.sndcpy/.MainActivity

echo ""
echo "Click audio capture dialog on your device!"
echo "Press Enter once audio capture authorized..."
read dummy

"$PLAYER" -autoexit -nodisp -probesize 32 -f s16le -ar 48000 -ac 2 -sync ext tcp://localhost:"$SNDCPY_PORT"
